### PR TITLE
Create handling-version-info

### PR DESCRIPTION
**Pull request by jallpatell**
Add info on how to handle versioning #31

### CODE REVIEW

**Comment by franzihei** [comment]
Hi @jallpatell - The issue you are referring to was about adding a section on how to handle the versioning of the documentation in the documentation translations (this is the github org for Solidity documentation translations), not about how to do versioning for smart contracts.

**Comment by r0qs** [comment]
Thanks @jallpatell, but as @franzihei said your PR does not solve the problem of the issue https://github.com/solidity-docs/.github/issues/31, so I'm closing this PR for now.

@franzihei, maybe we should update the issue description so it is more clear that it is about the versioning of the documentations.

**Comment by jallpatell** [comment]
Sorry for making error, just a newbie.  Excuse.

**Comment by franzihei** [comment]
@r0qs yes I can update the issue description a bit! just to be clear: I think this is an issue that can best be solved by us (one of the Solidity team members) - since we know how versioning works from our side.

**Comment by r0qs** [comment]
> @r0qs yes I can update the issue description a bit! just to be clear: I think this is an issue that can best be solved by us (one of the Solidity team members) - since we know how versioning works from our side.

Agreed :)

**Pull request closed without merging**
